# Generated by Django 4.2.20 on 2025-04-18 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la sede')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la facultad')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.AlterModelOptions(
            name='examtemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plantilla de Examen', 'verbose_name_plural': 'Plantillas de Examen'},
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='campuses',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='faculties',
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(upload_to='institution_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['exam_type', 'year'], name='material_ex_exam_ty_7ccfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['subject'], name='material_ex_subject_535ba4_idx'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='material.institution', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='material.institution', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.faculty', verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.campus', verbose_name='Sede'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('name', 'institution')},
        ),
    ]
