# Generated by Django 4.2.20 on 2025-06-17 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtemplate',
            name='exam_group',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='partial_number',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='resolution_time_number',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='resolution_time_unit',
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='resolution_time',
            field=models.CharField(default='60 minutos', help_text='Ej: 90 minutos, 2 horas', max_length=50, verbose_name='Duración del examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS personalizado para la plantilla', verbose_name='Estilos CSS'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_type',
            field=models.CharField(choices=[('1er_parcial', '1er. Parcial'), ('2do_parcial', '2do. Parcial'), ('3er_parcial', '3er. Parcial'), ('final', 'Final'), ('recuperatorio', 'Recuperatorio'), ('practico', 'Práctico')], max_length=20, verbose_name='Tipo de examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='exam_templates/logos/', verbose_name='Logo institucional'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, to='material.learningoutcome', verbose_name='Resultados de aprendizaje'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='shift',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='topics_to_evaluate',
            field=models.TextField(blank=True, help_text='Listado de temas incluidos en el examen', verbose_name='Temas a evaluar'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='year',
            field=models.PositiveIntegerField(default=2023, verbose_name='Año académico'),
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['exam_type', 'year'], name='material_ex_exam_ty_7ccfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['subject'], name='material_ex_subject_535ba4_idx'),
        ),
    ]
