# Generated by Django 4.2.20 on 2025-04-18 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='institution_logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='institution_logo',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='professor_name',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='contenido',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='exam_group',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='individual', max_length=10, verbose_name='Modalidad grupal'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='partial_number',
            field=models.CharField(blank=True, choices=[('1ro', 'Primer Parcial'), ('2do', 'Segundo Parcial'), ('3ro', 'Tercer Parcial'), ('4to', 'Cuarto Parcial')], max_length=10, null=True, verbose_name='Número de parcial'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='resolution_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de resolución'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='shift',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10, null=True, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados de aprendizaje'),
        ),
        migrations.AddField(
            model_name='topic',
            name='importance',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Importancia (1-5)'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='career_name',
            field=models.CharField(max_length=255, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_mode',
            field=models.CharField(choices=[('oral', 'Oral'), ('escrito', 'Escrito')], max_length=10, verbose_name='Modalidad de examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_type',
            field=models.CharField(choices=[('final', 'Final'), ('parcial', 'Parcial')], max_length=10, verbose_name='Tipo de examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='notes_and_recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Notas y recomendaciones'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='topics_to_evaluate',
            field=models.TextField(blank=True, null=True, verbose_name='Temas a evaluar'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('level', models.PositiveSmallIntegerField(help_text='Nivel de dominio (1: Básico, 2: Intermedio, 3: Avanzado)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='material.subject')),
            ],
            options={
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.institution')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'unique_together': {('name', 'institution')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, to='material.learningoutcome', verbose_name='Resultados de aprendizaje'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.faculty', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.institution', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, to='material.learningoutcome', verbose_name='Resultados de aprendizaje'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculties',
            field=models.ManyToManyField(blank=True, to='material.faculty', verbose_name='Facultades'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='material.institution', verbose_name='Instituciones'),
        ),
    ]
