# Generated by Django 4.2.20 on 2025-08-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['subject', 'level', 'created_at'], 'verbose_name': 'Resultado de Aprendizaje', 'verbose_name_plural': 'Resultados de Aprendizaje'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.RemoveIndex(
            model_name='learningoutcome',
            name='material_le_subject_906745_idx',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='learning_outcomes',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1 - Básico'), (2, 'Nivel 2 - Intermedio'), (3, 'Nivel 3 - Avanzado'), (4, 'Nivel 4 - Experto'), (5, 'Nivel 5 - Maestría')], default=1, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='description',
            field=models.TextField(help_text='Descripción detallada del resultado de aprendizaje', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='material.subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='subject_set', to='material.career', verbose_name='Carreras'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Nombre de la materia', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['subject', 'level'], name='material_le_subject_08abc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningoutcome',
            constraint=models.UniqueConstraint(fields=('subject', 'description'), name='unique_outcome_description_per_subject'),
        ),
    ]
