# Generated by Django 5.1.6 on 2025-02-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
