# Generated by Django 4.2.20 on 2025-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionv2',
            options={'ordering': ['name'], 'verbose_name': 'Institución V2', 'verbose_name_plural': 'Instituciones V2'},
        ),
        migrations.AlterField(
            model_name='institutionv2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='institutionv2',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la institución está activa en el sistema', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='institutionv2',
            name='logo',
            field=models.ImageField(blank=True, help_text='Subir imagen del logo institucional', null=True, upload_to='institution_logos_v2/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='institutionv2',
            name='name',
            field=models.CharField(help_text='Nombre completo de la institución', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='institutionv2',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='institutionv2',
            index=models.Index(fields=['name'], name='material_in_name_68b523_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionv2',
            index=models.Index(fields=['is_active'], name='material_in_is_acti_5ed340_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutionv2',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_institution_name'),
        ),
    ]
