# Generated by Django 4.2.20 on 2025-05-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='material_qu_subject_80b130_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='material_qu_conteni_ce5f3f_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='Formatos: JPG, PNG, SVG', null=True, upload_to='answers/images/', verbose_name='Imagen de la respuesta (opcional)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Formatos: JPG, PNG, SVG', null=True, upload_to='questions/images/', verbose_name='Imagen de la pregunta (opcional)'),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_book',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Libro/Documento (opcional)'),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options_json',
            field=models.TextField(blank=True, null=True, verbose_name='Opciones (JSON)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Página de referencia (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.subtopic', verbose_name='Subtema (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.topic', verbose_name='Tema principal'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
