# Generated by Django 4.2.20 on 2025-04-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_institution_rename_nombre_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='website',
        ),
        migrations.AddField(
            model_name='institution',
            name='campuses',
            field=models.TextField(blank=True, help_text='Lista de sedes, separadas por comas'),
        ),
    ]
