# Generated by Django 4.2.20 on 2025-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_question_material_qu_subject_80b130_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Página de referencia'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados de aprendizaje (opcional)'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('contenido', 'source_page')},
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo de la carrera', max_length=255, unique=True, verbose_name='Nombre de la Carrera')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('campus', models.ManyToManyField(blank=True, related_name='careers_campus', to='material.campusv2', verbose_name='Campus')),
                ('faculties', models.ManyToManyField(blank=True, related_name='careers', to='material.facultyv2', verbose_name='Facultades')),
                ('subjects', models.ManyToManyField(blank=True, related_name='careers', to='material.subject', verbose_name='Materias')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
    ]
