# Generated by Django 4.2.20 on 2025-08-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_learningoutcome_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['subject', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='learningoutcome',
            name='unique_outcome_description_per_subject',
        ),
        migrations.RemoveIndex(
            model_name='learningoutcome',
            name='material_le_subject_08abc0_idx',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='level',
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='description',
            field=models.TextField(help_text='Descripción del resultado de aprendizaje', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='material.subject'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='learningoutcome',
            constraint=models.UniqueConstraint(fields=('subject', 'description'), name='unique_outcome_description'),
        ),
    ]
