# Generated by Django 4.2.20 on 2025-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_campus_faculty_alter_examtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('name', 'institution'), name='unique_campus_per_institution', violation_error_message='Ya existe una sede con este nombre en la institución'),
        ),
    ]
