# Generated by Django 4.2.20 on 2025-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_examtemplate_exam_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text="Ingrese un resultado por línea. Puede usar el formato 'Código: Descripción' o simplemente la descripción.", null=True, verbose_name='Resultados de aprendizaje'),
        ),
    ]
