# Generated by Django 4.2.20 on 2025-08-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0003_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtemplate',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.campusv2', verbose_name='Sede/Campus'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('domiciliario', 'Domiciliario'), ('hibrido', 'Híbrido'), ('otro', 'Otro')], default='presencial', max_length=20, verbose_name='Modalidad de examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('1er_parcial', '1er. Parcial'), ('2do_parcial', '2do. Parcial'), ('3er_parcial', '3er. Parcial'), ('final', 'Final'), ('recuperatorio', 'Recuperatorio'), ('practico', 'Práctico')], default='1er_parcial', max_length=20, verbose_name='Tipo de examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professor_exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Año académico'),
        ),
    ]
