# Generated by Django 4.2.20 on 2025-05-16 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_contenido_chapter_alter_question_source_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_core', models.BooleanField(default=True, help_text='Indica si es una materia troncal/obligatoria', verbose_name='Materia troncal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_subjects', to='material.institutionv2', verbose_name='Institución')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_institutions', to='material.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Relación Institución-Materia',
                'verbose_name_plural': 'Relaciones Institución-Materias',
                'ordering': ['-date_created'],
                'unique_together': {('institution', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_institutions', to='material.career', verbose_name='Carrera')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_careers', to='material.institutionv2', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Relación Institución-Carrera',
                'verbose_name_plural': 'Relaciones Institución-Carreras',
                'ordering': ['-date_created'],
                'unique_together': {('institution', 'career')},
            },
        ),
        migrations.CreateModel(
            name='CareerSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(blank=True, help_text='Semestre en que se cursa la materia', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Semestre')),
                ('is_optional', models.BooleanField(default=False, help_text='Indica si la materia es optativa', verbose_name='Optativa')),
                ('workload_hours', models.PositiveSmallIntegerField(blank=True, help_text='Horas totales de la materia', null=True, verbose_name='Carga horaria')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_subjects', to='material.career', verbose_name='Carrera')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_careers', to='material.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Relación Carrera-Materia',
                'verbose_name_plural': 'Relaciones Carrera-Materias',
                'ordering': ['semester', 'subject__name'],
                'unique_together': {('career', 'subject')},
            },
        ),
    ]
