# Generated by Django 4.2.20 on 2025-04-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_campus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='campus',
            name='unique_campus_per_institution',
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.institution'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.institution'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('name', 'institution'), name='unique_campus_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('name', 'institution'), name='unique_faculty_per_institution'),
        ),
    ]
