# Generated by Django 4.2.20 on 2025-08-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_learningoutcome_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['subject', 'created_at'], 'verbose_name': 'Resultado de Aprendizaje', 'verbose_name_plural': 'Resultados de Aprendizaje'},
        ),
        migrations.RemoveConstraint(
            model_name='learningoutcome',
            name='unique_outcome_description',
        ),
    ]
