# Generated by Django 4.2.20 on 2025-04-26 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0004_alter_campus_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.CheckConstraint(check=models.Q(('name__gt', '')), name='non_empty_name'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_institution_owner'),
        ),
    ]
