# Generated by Django 4.2.20 on 2025-08-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_examtemplate_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('domiciliario', 'Domiciliario'), ('hibrido', 'Híbrido'), ('otro', 'Otro')], default=None, max_length=20, null=True, verbose_name='Modalidad de examen'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('1er_parcial', '1er. Parcial'), ('2do_parcial', '2do. Parcial'), ('3er_parcial', '3er. Parcial'), ('final', 'Final'), ('recuperatorio', 'Recuperatorio'), ('practico', 'Práctico')], default=None, max_length=20, null=True, verbose_name='Tipo de examen'),
        ),
    ]
