# Generated by Django 4.2.20 on 2025-08-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_learningoutcome_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyv2',
            name='code',
        ),
    ]
