# Generated by Django 4.2.20 on 2025-08-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_facultyv2_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['subject__name', 'created_at'], 'verbose_name': 'Resultado de Aprendizaje', 'verbose_name_plural': 'Resultados de Aprendizaje'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='facultyv2',
            name='code',
            field=models.CharField(blank=True, help_text='Código de la facultad (opcional)', max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Legacy field - almacena outcomes en texto o JSON', null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='description',
            field=models.TextField(help_text='Texto completo del resultado de aprendizaje', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_relations', to='material.subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='careers',
            field=models.ManyToManyField(related_name='subject_careers', to='material.career'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
