# Generated by Django 4.2.20 on 2025-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_examtemplate_exam_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtemplate',
            name='resolution_time',
            field=models.CharField(blank=True, default=None, help_text='Ej: 90 minutos, 2 horas', max_length=50, null=True, verbose_name='Duración del examen'),
        ),
    ]
