# Generated by Django 5.1.6 on 2025-02-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
