# Generated by Django 4.2.20 on 2025-08-02 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_examtemplate_resolution_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['subject', 'code'], 'verbose_name': 'Resultado de Aprendizaje', 'verbose_name_plural': 'Resultados de Aprendizaje'},
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='code',
            field=models.CharField(editable=False, help_text='Generado automáticamente al guardar', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], default=1, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='material.subject', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='learning_outcomes',
            field=models.TextField(blank=True, editable=False, help_text='Este campo será eliminado en futuras versiones. Use el modelo LearningOutcome.', null=True, verbose_name='[OBSOLETO] Resultados de aprendizaje (formato antiguo)'),
        ),
    ]
