# Generated by Django 4.2.20 on 2025-08-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_learningoutcome_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='material.subject', verbose_name='Materia'),
        ),
    ]
