# Generated by Django 5.0 on 2025-03-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_question_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('institution_name', models.CharField(max_length=255)),
                ('career_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('professor_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('final', 'Final'), ('parcial', 'Parcial')], max_length=10)),
                ('exam_mode', models.CharField(choices=[('oral', 'Oral'), ('escrito', 'Escrito')], max_length=10)),
                ('notes_and_recommendations', models.TextField()),
                ('topics_to_evaluate', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
