# Generated by Django 4.2.20 on 2025-08-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_learningoutcome_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_relations', to='material.subject', verbose_name='Materia'),
        ),
    ]
