# Generated by Django 5.0 on 2025-03-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_examtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['materia', 'topic', 'subtopic']},
        ),
        migrations.AddField(
            model_name='exam',
            name='materia',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='materia',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.materia'),
        ),
    ]
