# Generated by Django 4.2.20 on 2025-08-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_alter_learningoutcome_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyv2',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='facultyv2',
            name='unique_faculty_name_per_institution',
        ),
        migrations.RemoveField(
            model_name='facultyv2',
            name='code',
        ),
    ]
