# Generated by Django 4.2.20 on 2025-08-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0009_alter_facultyv2_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(help_text='Cambios en formato {campo: [valor_anterior, nuevo_valor]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Contenido Educativo', 'verbose_name_plural': 'Contenidos Educativos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['contenido', 'source_chapter', 'source_page'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contenido',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='content_type',
            field=models.CharField(choices=[('book', 'Libro'), ('paper', 'Artículo'), ('thesis', 'Tesis'), ('presentation', 'Presentación'), ('other', 'Otro')], default='book', max_length=20),
        ),
        migrations.AddField(
            model_name='contenido',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('analyzed', 'Analizado'), ('error', 'Error')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='contenido',
            name='total_chapters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo/Sección'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.subject'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando el contenido fue subido', verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.contenido'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy fácil'), (2, 'Fácil'), (3, 'Media'), (4, 'Difícil'), (5, 'Muy difícil')], default=3, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('true_false', 'Verdadero/Falso'), ('short_answer', 'Respuesta corta'), ('essay', 'Ensayo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.subtopic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['contenido', 'is_selected'], name='material_qu_conteni_7778f6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'topic'], name='material_qu_subject_33c77e_idx'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='material.question'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='options_json',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reference_book',
        ),
        migrations.RemoveField(
            model_name='question',
            name='unit',
        ),
    ]
