# Generated by Django 4.2.20 on 2025-08-09 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0010_questionversion_alter_contenido_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionversion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='contenido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['subject', 'topic', 'subtopic', 'difficulty'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='material_qu_conteni_7778f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='material_qu_subject_33c77e_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='total_chapters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='question',
            name='source_chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='source_unit',
        ),
        migrations.AddField(
            model_name='question',
            name='options_json',
            field=models.TextField(blank=True, null=True, verbose_name='Opciones (JSON)'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capítulo (opcional)'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/images/', verbose_name='Imagen de la respuesta (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(verbose_name='Texto de la respuesta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='material.contenido', verbose_name='Contenido relacionado'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dificultad (1-5)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Imagen de la pregunta (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('desarrollo', 'Desarrollo')], default='opcion_multiple', max_length=20, verbose_name='Tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Página de referencia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='material.subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.subtopic', verbose_name='Subtema (opcional)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.topic', verbose_name='Tema principal'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='QuestionVersion',
        ),
    ]
