# Generated by Django 4.2.20 on 2025-09-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0011_remove_questionversion_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField(verbose_name='Número de grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Examen Oral',
                'verbose_name_plural': 'Grupos de Examen Oral',
                'ordering': ['exam_set', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='OralExamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(verbose_name='Número de estudiante')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='material.oralexamgroup')),
            ],
            options={
                'verbose_name': 'Estudiante de Examen Oral',
                'verbose_name_plural': 'Estudiantes de Examen Oral',
                'ordering': ['group', 'student_number'],
            },
        ),
        migrations.CreateModel(
            name='OralExamStudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden de la pregunta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.oralexamstudent')),
            ],
            options={
                'verbose_name': 'Pregunta de Estudiante',
                'verbose_name_plural': 'Preguntas de Estudiantes',
                'ordering': ['student', 'order'],
                'unique_together': {('student', 'order')},
            },
        ),
        migrations.AddField(
            model_name='oralexamstudent',
            name='questions',
            field=models.ManyToManyField(through='material.OralExamStudentQuestion', to='material.question', verbose_name='Preguntas asignadas'),
        ),
        migrations.CreateModel(
            name='OralExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del conjunto de examen oral')),
                ('num_groups', models.PositiveIntegerField(help_text='Cantidad de grupos de estudiantes', verbose_name='Número de grupos')),
                ('students_per_group', models.PositiveIntegerField(help_text='Número de estudiantes en cada grupo', verbose_name='Estudiantes por grupo')),
                ('questions_per_student', models.PositiveIntegerField(default=3, help_text='Cantidad de preguntas que recibirá cada estudiante', verbose_name='Preguntas por estudiante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.subject', verbose_name='Materia')),
                ('topics', models.ManyToManyField(help_text='Seleccione los temas que se incluirán en el examen oral', to='material.topic', verbose_name='Temas a evaluar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Conjunto de Examen Oral',
                'verbose_name_plural': 'Conjuntos de Exámenes Orales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='oralexamgroup',
            name='exam_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='material.oralexamset'),
        ),
    ]
