# Generated by Django 4.2.20 on 2025-09-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_oralexamgroup_oralexamstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralexamset',
            name='total_students',
            field=models.PositiveIntegerField(default=10, help_text='Cantidad total de estudiantes que rendirán el examen', verbose_name='Total de estudiantes'),
            preserve_default=False,
        ),
    ]
