# Generated by Django 4.2.20 on 2025-09-19 for oral exam evaluation system

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_oralexamset_total_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralexamstudent',
            name='student_name',
            field=models.CharField(blank=True, help_text='Nombre completo del estudiante', max_length=255, null=True, verbose_name='Nombre del estudiante'),
        ),
        migrations.AddField(
            model_name='oralexamstudentquestion',
            name='evaluation',
            field=models.CharField(choices=[('bien', 'Bien'), ('regular', 'Regular'), ('mal', 'Mal'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10, verbose_name='Evaluación'),
        ),
        migrations.AddField(
            model_name='oralexamstudentquestion',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de evaluación'),
        ),
        migrations.AddField(
            model_name='oralexamstudentquestion',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
    ]
