# Generated by Django 4.2.20 on 2026-02-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_oralexamstudent_student_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyv2',
            options={'ordering': ['name'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AddField(
            model_name='question',
            name='ai_approved',
            field=models.BooleanField(blank=True, help_text='True=Aprobada, False=Rechazada, NULL=Sin revisar', null=True, verbose_name='Aprobada por usuario'),
        ),
        migrations.AddField(
            model_name='question',
            name='generated_by_ai',
            field=models.BooleanField(default=False, help_text='Indica si esta pregunta fue generada automáticamente por IA', verbose_name='Generada por IA'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_chapters_json',
            field=models.TextField(blank=True, help_text='JSON con información de los capítulos de donde se generó', null=True, verbose_name='Capítulos fuente (JSON)'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='year',
            field=models.PositiveIntegerField(default=2026, verbose_name='Año académico'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyv2',
            unique_together={('institution', 'name')},
        ),
    ]
