# Generated by Django 4.2.20 on 2026-04-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_question_bloom_level_question_completar_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['topic', 'subtopic', 'difficulty'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='career_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('escrito', 'Escrito')], max_length=10, null=True, verbose_name='Modalidad de examen'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('final', 'Final'), ('parcial', 'Parcial')], max_length=10, null=True, verbose_name='Tipo de examen'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
