# Generated by Django 4.2.20 on 2026-04-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_nullable_exam_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='alumno',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Alumno/a'),
        ),
        migrations.AddField(
            model_name='exam',
            name='campus_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sede (texto)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='curso',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date_str',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fecha (texto)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='faculty_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facultad (texto)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institución (texto)'),
        ),
    ]
