# Generated by Django 4.2.20 on 2026-04-20 01:33

from django.db import migrations, models


def populate_snapshots(apps, schema_editor):
    """Puebla los campos snapshot en registros existentes con los nombres actuales de las FK."""
    Exam = apps.get_model('material', 'Exam')
    ExamTemplate = apps.get_model('material', 'ExamTemplate')

    # ── Exam: poblar subject_name ──────────────────────────────────────
    for exam in Exam.objects.select_related('subject').iterator():
        if exam.subject and not exam.subject_name:
            exam.subject_name = exam.subject.name
            exam.save(update_fields=['subject_name'])

    # ── ExamTemplate: poblar todos los campos snapshot ─────────────────
    for tmpl in ExamTemplate.objects.select_related(
        'institution', 'faculty', 'campus', 'career', 'subject'
    ).iterator():
        tmpl.institution_name_snapshot = tmpl.institution.name if tmpl.institution_id else ''
        tmpl.faculty_name_snapshot     = tmpl.faculty.name     if tmpl.faculty_id     else ''
        tmpl.campus_name_snapshot      = tmpl.campus.name      if tmpl.campus_id      else ''
        tmpl.career_name_snapshot      = tmpl.career.name      if tmpl.career_id      else ''
        tmpl.subject_name_snapshot     = tmpl.subject.name     if tmpl.subject_id     else ''
        # topics_snapshot: split del texto topics_to_evaluate
        raw = tmpl.topics_to_evaluate or ''
        tmpl.topics_snapshot = [t.strip() for t in raw.split('\n') if t.strip()]
        # outcomes_snapshot: via M2M — accedido como queryset normal en data migrations
        tmpl.outcomes_snapshot = list(
            tmpl.learning_outcomes.values_list('description', flat=True)
        )
        tmpl.save(update_fields=[
            'institution_name_snapshot', 'faculty_name_snapshot', 'campus_name_snapshot',
            'career_name_snapshot', 'subject_name_snapshot', 'topics_snapshot', 'outcomes_snapshot',
        ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0020_profile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='outcomes_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Resultados de aprendizaje (snapshot)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Materia (texto)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='topics_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Temas (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='campus_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sede (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='career_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Carrera (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='faculty_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facultad (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='institution_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institución (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='outcomes_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Resultados de aprendizaje (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='subject_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Materia (snapshot)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='topics_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Temas (snapshot)'),
        ),
        migrations.RunPython(populate_snapshots, reverse_code=noop),
    ]

