# Generated by Django 4.2.20 on 2026-05-04 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0021_snapshot_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('body', models.TextField(help_text='Texto completo de la rúbrica de evaluación', verbose_name='Contenido de la rúbrica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_exam', models.BooleanField(default=True, help_text='Si está activo, la rúbrica se incluye al imprimir el examen', verbose_name='Mostrar en examen')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_rubrics', to='material.exam', verbose_name='Examen')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_rubrics', to='material.rubric', verbose_name='Rúbrica')),
            ],
            options={
                'verbose_name': 'Rúbrica de examen',
                'verbose_name_plural': 'Rúbricas de examen',
                'ordering': ['position', 'id'],
                'unique_together': {('exam', 'rubric')},
            },
        ),
    ]
