# Generated by Django 4.2.20 on 2026-05-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0022_rubric_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='body',
            field=models.TextField(blank=True, help_text='Texto libre (legacy). Las rúbricas nuevas usan la grilla estructurada.', null=True, verbose_name='Contenido de la rúbrica'),
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='material.rubric', verbose_name='Rúbrica')),
            ],
            options={
                'verbose_name': 'Nivel de rúbrica',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Criterio')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='material.rubric', verbose_name='Rúbrica')),
            ],
            options={
                'verbose_name': 'Criterio de rúbrica',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='material.rubriccriterion', verbose_name='Criterio')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='material.rubriclevel', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Celda de rúbrica',
                'unique_together': {('criterion', 'level')},
            },
        ),
    ]
