# Generated by Django 4.2.20 on 2026-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0026_question_image_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionv2',
            name='logo_b64',
            field=models.TextField(blank=True, help_text='Copia del logo en Base64 para producción sin filesystem persistente', null=True, verbose_name='Logo (Base64)'),
        ),
        migrations.AlterField(
            model_name='useraiconfig',
            name='provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI (GPT-4o, GPT-4, etc.)'), ('gemini', 'Google Gemini (Gemini 1.5 Flash / Pro)'), ('anthropic', 'Anthropic (Claude 3, etc.)'), ('groq', 'Groq (Llama, Mixtral)'), ('mistral', 'Mistral AI'), ('openrouter', 'OpenRouter'), ('openai_compatible', 'Compatible con OpenAI (URL personalizada)')], max_length=30, verbose_name='Proveedor'),
        ),
    ]
