# Generated by Django 4.2.20 on 2026-07-16 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0029_merge_0028_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Calibri', 'Calibri'), ('Helvetica', 'Helvetica')], default='Arial', max_length=50)),
                ('tamano_fuente', models.PositiveSmallIntegerField(default=11)),
                ('interlineado', models.FloatField(default=1.15)),
                ('margen_superior_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('margen_inferior_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('margen_izquierdo_cm', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('margen_derecho_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('color_titulo', models.CharField(blank=True, default='', max_length=7)),
                ('color_texto', models.CharField(blank=True, default='', max_length=7)),
                ('nombre', models.CharField(max_length=120)),
                ('es_default', models.BooleanField(default=False, verbose_name='Predeterminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos_impresion', to='material.institutionv2')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos_impresion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato de impresión',
                'verbose_name_plural': 'Formatos de impresión',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormatoImpresionAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Calibri', 'Calibri'), ('Helvetica', 'Helvetica')], default='Arial', max_length=50)),
                ('tamano_fuente', models.PositiveSmallIntegerField(default=11)),
                ('interlineado', models.FloatField(default=1.15)),
                ('margen_superior_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('margen_inferior_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('margen_izquierdo_cm', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('margen_derecho_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('color_titulo', models.CharField(blank=True, default='', max_length=7)),
                ('color_texto', models.CharField(blank=True, default='', max_length=7)),
                ('nombre_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formato_impresion_asignado', to='material.exam')),
                ('formato_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_asignados', to='material.formatoimpresion')),
            ],
            options={
                'verbose_name': 'Formato de impresión asignado',
                'verbose_name_plural': 'Formatos de impresión asignados',
            },
        ),
        migrations.AddConstraint(
            model_name='formatoimpresion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_default', True), ('institution__isnull', True), ('user__isnull', False)), fields=('user', 'es_default'), name='unique_default_print_format_per_user'),
        ),
        migrations.AddConstraint(
            model_name='formatoimpresion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_default', True), ('institution__isnull', False), ('user__isnull', True)), fields=('institution', 'es_default'), name='unique_default_print_format_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='formatoimpresion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_default', True), ('institution__isnull', True), ('user__isnull', True)), fields=('es_default',), name='unique_default_print_format_global'),
        ),
    ]
