# Generated by Django 4.2.20 on 2026-07-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0030_formatoimpresion_formatoimpresionasignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='contenidos/'),
        ),
    ]
