# Generated by Django 4.2.20 on 2026-07-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0031_alter_contenido_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('final', 'Final'), ('parcial', 'Parcial')], max_length=20, null=True, verbose_name='Tipo de examen'),
        ),
    ]
