# Generated by Django 4.2.20 on 2026-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0036_remove_rubric_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gemini', max_length=30, verbose_name='Proveedor')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='API Key (cifrada)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración IA Global (demo)',
                'verbose_name_plural': 'Configuración IA Global (demo)',
            },
        ),
    ]
