# Generated by Django 4.2.20 on 2026-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0037_globalaiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor(es)'),
        ),
    ]
