# Generated by Django 4.2.20 on 2026-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0039_fix_exam_model_duplicate_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campusv2',
            name='unique_campus_name_per_institution',
        ),
        migrations.AlterUniqueTogether(
            name='facultyv2',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='campusv2',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('institution', 'name'), name='unique_active_campus_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='facultyv2',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('institution', 'name'), name='unique_active_faculty_name_per_institution'),
        ),
    ]
