# Generated by Django 4.2.20 on 2026-07-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0040_campus_faculty_unique_only_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'verbose_name': 'Subtema', 'verbose_name_plural': 'Subtemas'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
