# Generated by Django 4.2.20 on 2026-07-30 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0042_seed_content_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sharing_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Grupo de confianza',
                'verbose_name_plural': 'Grupos de confianza',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_shares', to='material.sharinggroup', verbose_name='Grupo')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_shares', to=settings.AUTH_USER_MODEL, verbose_name='Compartida por')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shares', to='material.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia compartida',
                'verbose_name_plural': 'Materias compartidas',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'subject', 'shared_by')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='material.sharinggroup', verbose_name='Grupo')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de grupo',
                'verbose_name_plural': 'Membresías de grupo',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
