# Generated by Django 4.2.20 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0043_grupos_de_confianza'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalaiconfig',
            name='quota_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cupo verificado'),
        ),
        migrations.AddField(
            model_name='globalaiconfig',
            name='quota_limit_requests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Límite de solicitudes'),
        ),
        migrations.AddField(
            model_name='globalaiconfig',
            name='quota_limit_tokens',
            field=models.IntegerField(blank=True, null=True, verbose_name='Límite de tokens (ventana)'),
        ),
        migrations.AddField(
            model_name='globalaiconfig',
            name='quota_remaining_requests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Solicitudes restantes'),
        ),
        migrations.AddField(
            model_name='globalaiconfig',
            name='quota_remaining_tokens',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tokens restantes (ventana)'),
        ),
        migrations.AddField(
            model_name='globalaiconfig',
            name='quota_requests_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reinicio de solicitudes'),
        ),
    ]
