# Generated by Django 4.2.20 on 2026-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0044_globalaiconfig_quota_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraiconfig',
            name='source',
            field=models.CharField(choices=[('shared_demo', 'IA de prueba gratuita de EducaApp (limitada)'), ('ollama_local', 'IA Local (Ollama)'), ('byok', 'Mi propia API Key (BYOK)'), ('institutional', 'Configuración de la Institución')], default='ollama_local', max_length=20, verbose_name='Fuente de IA'),
        ),
    ]
