# Generated by Django 4.2.20 on 2026-08-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0045_alter_useraiconfig_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqMonitorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('success', models.BooleanField(default=False, verbose_name='Corrida sin errores')),
                ('target_questions', models.PositiveIntegerField(default=30, verbose_name='Preguntas pedidas')),
                ('total_generated', models.PositiveIntegerField(default=0, verbose_name='Preguntas generadas')),
                ('met_target', models.BooleanField(default=False, verbose_name='Cumplió el objetivo')),
                ('empty_questions', models.PositiveIntegerField(default=0, verbose_name='Preguntas vacías')),
                ('duplicate_questions', models.PositiveIntegerField(default=0, verbose_name='Preguntas duplicadas')),
                ('failed_chunks', models.PositiveIntegerField(default=0, verbose_name='Fragmentos fallidos')),
                ('elapsed_seconds', models.FloatField(blank=True, null=True, verbose_name='Duración (seg)')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Motivo de falla')),
                ('detail', models.TextField(blank=True, verbose_name='Detalle')),
                ('quota_remaining_requests', models.IntegerField(blank=True, null=True)),
                ('quota_limit_requests', models.IntegerField(blank=True, null=True)),
                ('quota_remaining_tokens', models.IntegerField(blank=True, null=True)),
                ('quota_limit_tokens', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Monitoreo de Groq — corrida',
                'verbose_name_plural': 'Monitoreo de Groq — corridas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroqMonitorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activo')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='Intervalo (minutos)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Se apaga solo')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última corrida')),
            ],
            options={
                'verbose_name': 'Monitoreo de Groq — configuración',
                'verbose_name_plural': 'Monitoreo de Groq — configuración',
            },
        ),
    ]
