# Generated by Django 4.2.20 on 2026-08-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0046_groq_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='groqmonitorrun',
            name='fixture',
            field=models.CharField(default='easy', max_length=20, verbose_name='Documento usado'),
        ),
    ]
