# Generated by Django 4.2.20 on 2026-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0047_groq_monitor_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visual_theme',
            field=models.CharField(choices=[('default', 'EducaApp'), ('slack', 'Slack'), ('bmw', 'BMW'), ('linear', 'Linear'), ('figma', 'Figma'), ('clay', 'Clay')], default='default', help_text='Skin de colores/tipografía elegido por el usuario para la interfaz.', max_length=20, verbose_name='Tema visual'),
        ),
    ]
