# Generated by Django 4.2.20 on 2026-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0048_profile_visual_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoimpresion',
            name='tamano_hoja',
            field=models.CharField(choices=[('A4', 'A4 (21,0 x 29,7 cm)'), ('Carta', 'Carta / Letter (21,6 x 27,9 cm)'), ('Oficio', 'Oficio / Legal (21,6 x 33,0 cm)')], default='A4', max_length=10),
        ),
        migrations.AddField(
            model_name='formatoimpresionasignado',
            name='tamano_hoja',
            field=models.CharField(choices=[('A4', 'A4 (21,0 x 29,7 cm)'), ('Carta', 'Carta / Letter (21,6 x 27,9 cm)'), ('Oficio', 'Oficio / Legal (21,6 x 33,0 cm)')], default='A4', max_length=10),
        ),
    ]
