# Generated by Django 4.2.20 on 2026-08-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0049_formatoimpresion_tamano_hoja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='topics_to_evaluate',
            field=models.TextField(blank=True, null=True, verbose_name='Tópicos a evaluar'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='topics_to_evaluate',
            field=models.TextField(blank=True, help_text='Listado de tópicos incluidos en el examen', verbose_name='Tópicos a evaluar'),
        ),
    ]
