# Generated by Django 4.2.20 on 2026-08-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0050_alter_exam_topics_to_evaluate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'verbose_name': 'Sub-tópico', 'verbose_name_plural': 'Sub-tópicos'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Sub-tópico'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.topic', verbose_name='Tópico relacionado'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Tópico'),
        ),
    ]
