# Generated by Django 4.2.20 on 2026-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0052_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqVisionTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('model_name', models.CharField(max_length=150, verbose_name='Modelo')),
                ('success', models.BooleanField(default=False, verbose_name='Corrida sin errores')),
                ('response_text', models.TextField(blank=True, verbose_name='Respuesta del modelo')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('elapsed_seconds', models.FloatField(blank=True, null=True, verbose_name='Duración (seg)')),
                ('quota_remaining_requests', models.IntegerField(blank=True, null=True)),
                ('quota_limit_requests', models.IntegerField(blank=True, null=True)),
                ('quota_remaining_tokens', models.IntegerField(blank=True, null=True)),
                ('quota_limit_tokens', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Monitoreo de Groq — prueba de visión',
                'verbose_name_plural': 'Monitoreo de Groq — pruebas de visión',
                'ordering': ['-created_at'],
            },
        ),
    ]
