# Generated by Django 4.2.20 on 2026-08-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0053_groqvisiontestrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMonitorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activo')),
                ('provider', models.CharField(default='gemini', max_length=30, verbose_name='Proveedor')),
                ('model', models.CharField(default='gemini-2.5-flash', max_length=150, verbose_name='Modelo')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='Intervalo (minutos)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Se apaga solo')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última corrida')),
            ],
            options={
                'verbose_name': 'Monitoreo de visión — configuración',
                'verbose_name_plural': 'Monitoreo de visión — configuración',
            },
        ),
        migrations.AddField(
            model_name='groqvisiontestrun',
            name='content_check_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Leyó bien la imagen'),
        ),
    ]
