# Generated by Django 4.2.20 on 2026-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0054_visionmonitorschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField(verbose_name='Prompt (con placeholders)')),
                ('temperature', models.FloatField(default=0.2, verbose_name='Temperature')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt de generación IA',
                'verbose_name_plural': 'Prompt de generación IA',
            },
        ),
    ]
