# Generated by Django 4.2.20 on 2026-08-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0055_questiongenerationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_seed_demo',
            field=models.BooleanField(default=False, help_text='Sembrada por seed_demo_content para el asistente de configuración — no es una materia real de ningún docente.', verbose_name='Materia semilla del sistema (demo)'),
        ),
    ]
