# Generated by Django 4.2.20 on 2026-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0057_mark_seed_demo_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='is_seed_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionv2',
            name='is_seed_demo',
            field=models.BooleanField(default=False),
        ),
    ]
