# Generated by Django 4.2.20 on 2026-08-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0059_mark_seed_institutions_and_careers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Respuesta de seguridad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('primera_mascota', 'Nombre de la primera mascota'), ('apellido_soltera_materno', 'Apellido de soltera materno'), ('ciudad_nacimiento', 'Ciudad de nacimiento'), ('comida_favorita', 'Comida favorita'), ('segundo_nombre_padre', 'Segundo nombre del padre'), ('marca_primer_auto', 'Marca del primer auto'), ('calle_donde_crecio', 'Nombre de la calle donde creció'), ('equipo_futbol', 'Equipo de fútbol preferido')], max_length=50, verbose_name='Pregunta de seguridad'),
        ),
    ]
