# Generated by Django 4.2.20 on 2026-08-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0061_fix_leaked_fotosintesis_prompt_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerSubject',
        ),
    ]
