# Generated by Django 4.2.20 on 2026-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0067_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visual_theme',
            field=models.CharField(choices=[('default', 'EducaApp'), ('slack', 'Slack'), ('linear', 'Linear'), ('figma', 'Figma')], default='default', help_text='Skin de colores/tipografía elegido por el usuario para la interfaz.', max_length=20, verbose_name='Tema visual'),
        ),
    ]
