# Generated by Django 4.2.20 on 2026-08-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0069_backfill_removed_visual_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='print_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_templates', to='material.formatoimpresion', verbose_name='Formato de impresión'),
        ),
    ]
