# Generated by Django 4.2.20 on 2026-08-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0070_examtemplate_print_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtemplate',
            name='resolution_time',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='topics_snapshot',
        ),
        migrations.RemoveField(
            model_name='examtemplate',
            name='topics_to_evaluate',
        ),
    ]
