# Generated by Django 4.2.20 on 2026-08-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0071_remove_examtemplate_resolution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Notas y recomendaciones'),
        ),
    ]
