# Generated by Django 4.2.20 on 2026-08-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0072_alter_exam_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='notes_and_recommendations',
        ),
    ]
