# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0073_remove_exam_notes_and_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visual_theme',
            field=models.CharField(choices=[('default', 'EducaApp'), ('slack', 'Slack'), ('linear', 'Linear'), ('figma', 'Figma'), ('miro', 'Miro'), ('pinterest', 'Pinterest'), ('replicate', 'Replicate'), ('starbucks', 'Starbucks')], default='default', help_text='Skin de colores/tipografía elegido por el usuario para la interfaz.', max_length=20, verbose_name='Tema visual'),
        ),
    ]
