# Generated by Django 4.2.20 on 2026-08-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0074_alter_profile_visual_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre de la plantilla'),
        ),
    ]
