# Generated by Django 4.2.20 on 2026-08-14 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0075_examtemplate_add_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='rubrics',
            field=models.ManyToManyField(blank=True, related_name='exam_templates', to='material.rubric', verbose_name='Rúbricas'),
        ),
        migrations.CreateModel(
            name='RubricShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_shares', to='material.sharinggroup', verbose_name='Grupo')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shares', to='material.rubric', verbose_name='Rúbrica')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_shares', to=settings.AUTH_USER_MODEL, verbose_name='Compartida por')),
            ],
            options={
                'verbose_name': 'Rúbrica compartida',
                'verbose_name_plural': 'Rúbricas compartidas',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'rubric', 'shared_by')},
            },
        ),
    ]
