# Generated by Django 4.2.20 on 2026-08-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0077_alter_monitor_runs_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.PositiveSmallIntegerField(verbose_name='Número de área')),
                ('area_name', models.CharField(max_length=100, verbose_name='Área')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Orden')),
                ('text', models.CharField(max_length=300, verbose_name='Qué probar')),
                ('target_url_name', models.CharField(blank=True, help_text='Nombre de URL (namespace material:) al que apunta el link "Ir a esta pantalla". Vacío si no aplica.', max_length=100, verbose_name='Ruta relacionada')),
                ('admin_only', models.BooleanField(default=False, verbose_name='Solo testers admin')),
            ],
            options={
                'verbose_name': 'Ítem de checklist de testing',
                'verbose_name_plural': 'Ítems de checklist de testing',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='is_tester',
            field=models.BooleanField(default=False, help_text='Ve el panel de Modo Testing dentro de la app, para ir marcando el checklist de pruebas.', verbose_name='Es tester (UAT)'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'Funcionó bien'), ('problemas', 'Funcionó con problemas'), ('no_ok', 'No funcionó')], default='pendiente', max_length=12, verbose_name='Resultado')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='material.testchecklistitem', verbose_name='Ítem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Tester')),
            ],
            options={
                'verbose_name': 'Resultado de testing',
                'verbose_name_plural': 'Resultados de testing',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
