# Generated by Django 4.2.20 on 2026-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0078_testchecklistitem_profile_is_tester_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_tester',
            field=models.BooleanField(default=False, help_text='La cuenta que se crea con este link nace con profile.is_tester=True — resuelve que no hay usuario a quien marcar como tester antes de que exista.', verbose_name='Es invitación de testing (UAT)'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='test_stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Etapa 1 — Contenido e IA'), (2, 'Etapa 2 — Exámenes y evaluación'), (3, 'Etapa 3 — Organización y colaboración')], null=True, verbose_name='Etapa de testing asignada'),
        ),
        migrations.AddField(
            model_name='profile',
            name='test_stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Etapa 1 — Contenido e IA'), (2, 'Etapa 2 — Exámenes y evaluación'), (3, 'Etapa 3 — Organización y colaboración')], help_text='Vacío = ve el checklist completo. Se completa solo al aceptar una invitación de testing con etapa asignada — no hace falta tocarlo a mano.', null=True, verbose_name='Etapa de testing asignada'),
        ),
        migrations.AddField(
            model_name='testchecklistitem',
            name='stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Etapa 1 — Contenido e IA'), (2, 'Etapa 2 — Exámenes y evaluación'), (3, 'Etapa 3 — Organización y colaboración')], help_text='Vacío = aparece para cualquier tester sin importar la etapa que tenga asignada (ítems transversales como Alta y primer acceso o Apariencia).', null=True, verbose_name='Etapa'),
        ),
    ]
