# Generated by Django 4.2.20 on 2026-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0079_invitation_is_tester_invitation_test_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groqmonitorrun',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Modelo'),
        ),
    ]
