# Generated by Django 4.2.20 on 2026-08-19 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('material', '0079_invitation_is_tester_invitation_test_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_materia', models.CharField(blank=True, default='', max_length=20, verbose_name='N° de materia')),
                ('anio_cursada', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de cursada')),
                ('cuatrimestre_cursada', models.CharField(blank=True, default='', max_length=20, verbose_name='Cuatrimestre de cursada')),
            ],
            options={
                'verbose_name': 'Materia de la carrera',
                'verbose_name_plural': 'Materias de la carrera',
                'ordering': ['anio_cursada', 'numero_materia'],
            },
        ),
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('institucion', 'Institución'), ('facultad', 'Facultad'), ('carrera', 'Carrera'), ('materia', 'Materia')], max_length=15, verbose_name='Tipo')),
                ('nombre_propuesto', models.CharField(max_length=255, verbose_name='Nombre propuesto')),
                ('justificacion', models.TextField(blank=True, default='', verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('nota_admin', models.TextField(blank=True, default='', verbose_name='Nota del admin')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de catálogo',
                'verbose_name_plural': 'Solicitudes de catálogo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('materia', 'Materia (temas y preguntas)'), ('rubrica', 'Rúbrica'), ('plantilla', 'Plantilla de examen'), ('formato', 'Formato de impresión')], max_length=10, verbose_name='Tipo')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_shares', to='material.sharinggroup', verbose_name='Grupo')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_shares', to=settings.AUTH_USER_MODEL, verbose_name='Compartido por')),
            ],
            options={
                'verbose_name': 'Contenido compartido',
                'verbose_name_plural': 'Contenidos compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la unidad')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='rubricshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rubricshare',
            name='group',
        ),
        migrations.RemoveField(
            model_name='rubricshare',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='rubricshare',
            name='shared_by',
        ),
        migrations.AlterUniqueTogether(
            name='subjectshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subjectshare',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subjectshare',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='subjectshare',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['created_at'], 'verbose_name': 'Resultado de Aprendizaje', 'verbose_name_plural': 'Resultados de Aprendizaje'},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='careers',
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_topics', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(help_text='Nombre completo de la carrera', max_length=255, verbose_name='Nombre de la Carrera'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject', 'created_by')},
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='RubricShare',
        ),
        migrations.DeleteModel(
            name='SubjectShare',
        ),
        migrations.AddField(
            model_name='unidad',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.subject'),
        ),
        migrations.AddField(
            model_name='contentshare',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_shares', to='material.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to='material.career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to='material.facultyv2', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to='material.institutionv2', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_catalog_requests', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='careersubject',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.career'),
        ),
        migrations.AddField(
            model_name='careersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.subject'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='career_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_relations', to='material.careersubject', verbose_name='Materia en la carrera'),
        ),
        migrations.AddField(
            model_name='topic',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='material.unidad', verbose_name='Unidad'),
        ),
        # No se puede pasar de M2M "liso" a M2M con through= vía AlterField
        # (Django lo rechaza: "you cannot alter to or from M2M fields, or
        # add or remove through= on M2M fields") — se saca el campo viejo
        # (con su tabla puente autogenerada, sin datos que perder) y se
        # agrega de nuevo ya con through=CareerSubject.
        migrations.RemoveField(
            model_name='career',
            name='subjects',
        ),
        migrations.AddField(
            model_name='career',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='careers', through='material.CareerSubject', to='material.subject', verbose_name='Materias'),
        ),
        migrations.AlterUniqueTogether(
            name='unidad',
            unique_together={('subject', 'created_by', 'name')},
        ),
        migrations.AddConstraint(
            model_name='contentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'materia')), fields=('group', 'shared_by', 'subject'), name='unique_materia_share'),
        ),
        migrations.AddConstraint(
            model_name='contentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'materia'), _negated=True), fields=('group', 'shared_by', 'content_type', 'object_id'), name='unique_object_share'),
        ),
        migrations.AlterUniqueTogether(
            name='careersubject',
            unique_together={('career', 'subject')},
        ),
    ]
