# Generated by Django 4.2.20 on 2026-08-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0080_1_delete_orphaned_learningoutcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='career_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_relations', to='material.careersubject', verbose_name='Materia en la carrera'),
        ),
    ]
