# Generated by Django 4.2.20 on 2026-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0081_alter_learningoutcome_career_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='visto_por_solicitante',
            field=models.BooleanField(default=False, verbose_name='Visto por el solicitante'),
        ),
    ]
