# Generated by Django 4.2.20 on 2026-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0082_catalogrequest_visto_por_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='carrera_nueva',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Carrera (nueva)'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='facultad_nueva',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facultad (nueva)'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='institucion_nueva',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institución (nueva)'),
        ),
        migrations.AddField(
            model_name='catalogrequest',
            name='logo_propuesto',
            field=models.ImageField(blank=True, help_text='Solo si estás proponiendo una institución nueva', null=True, upload_to='catalog_request_logos/', verbose_name='Logo propuesto'),
        ),
    ]
