# Generated by Django 4.2.20 on 2026-08-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0083_catalogrequest_carrera_nueva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to='material.subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='logo_propuesto',
            field=models.ImageField(blank=True, help_text='Solo si se está proponiendo una institución nueva', null=True, upload_to='catalog_request_logos/', verbose_name='Logo propuesto'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='nombre_propuesto',
            field=models.TextField(verbose_name='Nombre propuesto'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='tipo',
            field=models.CharField(choices=[('institucion', 'Institución'), ('facultad', 'Facultad'), ('carrera', 'Carrera'), ('materia', 'Materia'), ('resultado_aprendizaje', 'Resultado de aprendizaje')], max_length=25, verbose_name='Tipo'),
        ),
    ]
