# Generated by Django 4.2.20 on 2026-08-19 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0084_catalogrequest_materia_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facultyv2',
            name='unique_active_faculty_name_per_institution',
        ),
        migrations.RemoveConstraint(
            model_name='institutionv2',
            name='unique_active_institution_name',
        ),
        migrations.AddField(
            model_name='career',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='career',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
        migrations.AddField(
            model_name='facultyv2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='facultyv2',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
        migrations.AddField(
            model_name='institutionv2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='institutionv2',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
        migrations.AddField(
            model_name='subject',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
        migrations.AddConstraint(
            model_name='facultyv2',
            constraint=models.UniqueConstraint(condition=models.Q(('es_catalogo_institucional', True), ('is_active', True)), fields=('institution', 'name'), name='unique_active_faculty_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='institutionv2',
            constraint=models.UniqueConstraint(condition=models.Q(('es_catalogo_institucional', True), ('is_active', True)), fields=('name',), name='unique_active_institutional_institution_name'),
        ),
    ]
