# Generated by Django 4.2.20 on 2026-08-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0086_backfill_subject_es_catalogo_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='lote_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Lote'),
        ),
    ]
