# Generated by Django 4.2.20 on 2026-08-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0087_catalogrequest_lote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogrequest',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='material.career', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='material.facultyv2', verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='material.institutionv2', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='material.subject', verbose_name='Materia'),
        ),
    ]
