# Generated by Django 4.2.20 on 2026-08-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0088_alter_catalogrequest_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='institucion_sigla_nueva',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Sigla de la institución (nueva)'),
        ),
        migrations.AddField(
            model_name='institutionv2',
            name='sigla',
            field=models.CharField(blank=True, default='', help_text='Opcional — permite encontrarla al buscar por sigla además de por nombre completo', max_length=20, verbose_name='Sigla'),
        ),
    ]
