# Generated by Django 4.2.20 on 2026-08-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0089_catalogrequest_institucion_sigla_nueva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groqmonitorrun',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Modelo'),
        ),
    ]
