# Generated by Django 4.2.20 on 2026-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0090_groqmonitorrun_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalaiconfig',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='institutionaiconfig',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='useraiconfig',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
    ]
