# Generated by Django 4.2.20 on 2026-08-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0091_remove_hardcoded_ai_model_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='learning_outcomes',
        ),
    ]
