# Generated by Django 4.2.20 on 2026-08-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0092_remove_subject_legacy_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='catedra',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cátedra'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='catedra',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cátedra'),
        ),
    ]
