# Generated by Django 4.2.20 on 2026-09-10 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('material', '0093_exam_catedra_examtemplate_catedra'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDeletionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_snapshot', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('visto', models.BooleanField(default=False, verbose_name='Visto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_deletion_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso de pregunta borrada',
                'verbose_name_plural': 'Avisos de preguntas borradas',
                'ordering': ['-created_at'],
            },
        ),
    ]
