# Generated by Django 4.2.20 on 2026-09-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0094_questiondeletionnotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiondeletionnotice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aviso de contenido compartido borrado', 'verbose_name_plural': 'Avisos de contenido compartido borrado'},
        ),
        migrations.AddField(
            model_name='questiondeletionnotice',
            name='resolution',
            field=models.CharField(choices=[('borrado', 'Se borró para todos'), ('copia', 'Se dejó una copia propia')], default='borrado', max_length=10),
        ),
    ]
