# Generated by Django 4.2.20 on 2026-09-11 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0095_alter_questiondeletionnotice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoimpresion',
            name='interlineado',
            field=models.FloatField(default=1.15, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresion',
            name='margen_derecho_cm',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresion',
            name='margen_inferior_cm',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresion',
            name='margen_izquierdo_cm',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresion',
            name='margen_superior_cm',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresion',
            name='tamano_fuente',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(72)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresionasignado',
            name='interlineado',
            field=models.FloatField(default=1.15, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresionasignado',
            name='margen_derecho_cm',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresionasignado',
            name='margen_inferior_cm',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresionasignado',
            name='margen_izquierdo_cm',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresionasignado',
            name='margen_superior_cm',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formatoimpresionasignado',
            name='tamano_fuente',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(72)]),
        ),
    ]
