# Generated by Django 4.2.20 on 2026-09-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0096_alter_formatoimpresion_interlineado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professor_exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
    ]
