# Generated by Django 4.2.20 on 2026-09-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0097_alter_exam_professor_alter_examtemplate_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralexamset',
            name='include_no_topic',
            field=models.BooleanField(default=False, help_text='Suma también las preguntas de la materia que no tienen un tópico asignado (no se pueden representar en el M2M "topics", que solo apunta a Topic reales).', verbose_name='Incluir preguntas sin tópico'),
        ),
    ]
