# Generated by Django 4.2.20 on 2026-09-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0098_oralexamset_include_no_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='resultado_aprendizaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='material.learningoutcome', verbose_name='Resultado de aprendizaje'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_outcomes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
    ]
