# Generated by Django 4.2.20 on 2026-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0100_merge_pinterest_into_replicate_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_view_prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Columnas y orden elegidos por el usuario en cada listado. Se edita desde el botón Columnas de cada listado.', verbose_name='Vistas de listados'),
        ),
    ]
