# Generated by Django 4.2.20 on 2026-10-09 01:03

from django.db import migrations, models
from django.db.models import Q


def ollama_sin_url_a_ia_publica(apps, schema_editor):
    """Quienes nunca eligieron nada (quedaron con el default viejo, Ollama, sin
    una dirección propia) pasan a la IA pública. Quien cargó una URL de Ollama
    a propósito conserva su elección."""
    UserAIConfig = apps.get_model('material', 'UserAIConfig')
    sin_url = Q(ollama_url__isnull=True) | Q(ollama_url='')
    UserAIConfig.objects.filter(source='ollama_local').filter(sin_url).update(source='shared_demo')


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0101_profile_list_view_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraiconfig',
            name='source',
            field=models.CharField(choices=[('shared_demo', 'IA pública gratuita de EducaApp (limitada)'), ('ollama_local', 'Servidor de IA propio (Ollama)'), ('byok', 'Mi propia API Key (BYOK)'), ('institutional', 'Configuración de la Institución')], default='shared_demo', max_length=20, verbose_name='Fuente de IA'),
        ),
        migrations.RunPython(ollama_sin_url_a_ia_publica, migrations.RunPython.noop),
    ]
