# Generated by Django 4.2.20 on 2026-10-09 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0102_ia_publica_por_defecto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subtopics', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
        migrations.AddField(
            model_name='topic',
            name='career_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='material.careersubject', verbose_name='Materia en la carrera'),
        ),
        migrations.AddField(
            model_name='topic',
            name='es_catalogo_institucional',
            field=models.BooleanField(default=True, verbose_name='En el catálogo institucional'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject', 'career_subject', 'created_by')},
        ),
    ]
