# Generated by Django 4.2.20 on 2026-10-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0103_topico_por_carrera_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrequest',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='material.topic', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='catalogrequest',
            name='tipo',
            field=models.CharField(choices=[('institucion', 'Institución'), ('facultad', 'Facultad'), ('carrera', 'Carrera'), ('materia', 'Materia'), ('resultado_aprendizaje', 'Resultado de aprendizaje'), ('topico', 'Tópico')], max_length=25, verbose_name='Tipo'),
        ),
    ]
