# Generated by Django 4.2.20 on 2026-10-09 02:39

from django.db import migrations, models


def usuarios_existentes_en_modo_avanzado(apps, schema_editor):
    """Las cuentas que ya existían siguen viendo la app como siempre (modo
    avanzado): el modo simple es el punto de partida de las cuentas nuevas, no un
    cambio que se les imponga a quienes ya la usan. Cada quien puede pasar al modo
    simple desde el menú lateral."""
    Profile = apps.get_model('material', 'Profile')
    Profile.objects.update(interface_mode='avanzado')


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0104_catalogrequest_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interface_mode',
            field=models.CharField(choices=[('simple', 'Modo simple'), ('avanzado', 'Modo avanzado')], default='simple', help_text='Simple: menú reducido y asistentes. Avanzado: el menú completo y los formularios de siempre.', max_length=10, verbose_name='Modo de la interfaz'),
        ),
        migrations.RunPython(usuarios_existentes_en_modo_avanzado, migrations.RunPython.noop),
    ]
